/*
 * Ergo blockchain explorer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * BlockchainStatsBlockSummary
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-09T08:14:50.203Z[GMT]")
public class BlockchainStatsBlockSummary {
  @SerializedName("total")
  private Integer total = null;

  @SerializedName("averageMiningTime")
  private Integer averageMiningTime = null;

  @SerializedName("totalCoins")
  private BigDecimal totalCoins = null;

  public BlockchainStatsBlockSummary total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Number of mined blocks
   * @return total
  **/
  @Schema(example = "12030", description = "Number of mined blocks")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public BlockchainStatsBlockSummary averageMiningTime(Integer averageMiningTime) {
    this.averageMiningTime = averageMiningTime;
    return this;
  }

   /**
   * Time between blocks in ms
   * @return averageMiningTime
  **/
  @Schema(example = "43201", description = "Time between blocks in ms")
  public Integer getAverageMiningTime() {
    return averageMiningTime;
  }

  public void setAverageMiningTime(Integer averageMiningTime) {
    this.averageMiningTime = averageMiningTime;
  }

  public BlockchainStatsBlockSummary totalCoins(BigDecimal totalCoins) {
    this.totalCoins = totalCoins;
    return this;
  }

   /**
   * Total mined coins
   * @return totalCoins
  **/
  @Schema(example = "238193891032", description = "Total mined coins")
  public BigDecimal getTotalCoins() {
    return totalCoins;
  }

  public void setTotalCoins(BigDecimal totalCoins) {
    this.totalCoins = totalCoins;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockchainStatsBlockSummary blockchainStatsBlockSummary = (BlockchainStatsBlockSummary) o;
    return Objects.equals(this.total, blockchainStatsBlockSummary.total) &&
        Objects.equals(this.averageMiningTime, blockchainStatsBlockSummary.averageMiningTime) &&
        Objects.equals(this.totalCoins, blockchainStatsBlockSummary.totalCoins);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, averageMiningTime, totalCoins);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockchainStatsBlockSummary {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    averageMiningTime: ").append(toIndentedString(averageMiningTime)).append("\n");
    sb.append("    totalCoins: ").append(toIndentedString(totalCoins)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
