/*
 * Ergo blockchain explorer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.ergoplatform.explorer.client.model.BlockExtension;
import org.ergoplatform.explorer.client.model.BlockHeader;
import org.ergoplatform.explorer.client.model.Transaction;
/**
 * Block with header and transactions
 */
@Schema(description = "Block with header and transactions")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-09T08:14:50.203Z[GMT]")
public class FullBlock {
  @SerializedName("header")
  private BlockHeader header = null;

  @SerializedName("blockTransactions")
  private List<Transaction> blockTransactions = new ArrayList<>();

  @SerializedName("adProofs")
  private String adProofs = null;

  @SerializedName("extension")
  private BlockExtension extension = null;

  public FullBlock header(BlockHeader header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @Schema(required = true, description = "")
  public BlockHeader getHeader() {
    return header;
  }

  public void setHeader(BlockHeader header) {
    this.header = header;
  }

  public FullBlock blockTransactions(List<Transaction> blockTransactions) {
    this.blockTransactions = blockTransactions;
    return this;
  }

  public FullBlock addBlockTransactionsItem(Transaction blockTransactionsItem) {
    this.blockTransactions.add(blockTransactionsItem);
    return this;
  }

   /**
   * Transaction objects
   * @return blockTransactions
  **/
  @Schema(required = true, description = "Transaction objects")
  public List<Transaction> getBlockTransactions() {
    return blockTransactions;
  }

  public void setBlockTransactions(List<Transaction> blockTransactions) {
    this.blockTransactions = blockTransactions;
  }

  public FullBlock adProofs(String adProofs) {
    this.adProofs = adProofs;
    return this;
  }

   /**
   * Get adProofs
   * @return adProofs
  **/
  @Schema(required = true, description = "")
  public String getAdProofs() {
    return adProofs;
  }

  public void setAdProofs(String adProofs) {
    this.adProofs = adProofs;
  }

  public FullBlock extension(BlockExtension extension) {
    this.extension = extension;
    return this;
  }

   /**
   * Get extension
   * @return extension
  **/
  @Schema(required = true, description = "")
  public BlockExtension getExtension() {
    return extension;
  }

  public void setExtension(BlockExtension extension) {
    this.extension = extension;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullBlock fullBlock = (FullBlock) o;
    return Objects.equals(this.header, fullBlock.header) &&
        Objects.equals(this.blockTransactions, fullBlock.blockTransactions) &&
        Objects.equals(this.adProofs, fullBlock.adProofs) &&
        Objects.equals(this.extension, fullBlock.extension);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, blockTransactions, adProofs, extension);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullBlock {\n");
    
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    blockTransactions: ").append(toIndentedString(blockTransactions)).append("\n");
    sb.append("    adProofs: ").append(toIndentedString(adProofs)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
