/*
 * Ergo blockchain explorer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * IOSummary
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-09T08:14:50.203Z[GMT]")
public class IOSummary {
  @SerializedName("totalСoinsTransferred")
  private BigDecimal totalСoinsTransferred = null;

  @SerializedName("totalFee")
  private BigDecimal totalFee = null;

  @SerializedName("feePerByte")
  private BigDecimal feePerByte = null;

  public IOSummary totalСoinsTransferred(BigDecimal totalСoinsTransferred) {
    this.totalСoinsTransferred = totalСoinsTransferred;
    return this;
  }

   /**
   * Total Coins Transferred
   * @return totalСoinsTransferred
  **/
  @Schema(example = "1042.23", required = true, description = "Total Coins Transferred")
  public BigDecimal getTotalСoinsTransferred() {
    return totalСoinsTransferred;
  }

  public void setTotalСoinsTransferred(BigDecimal totalСoinsTransferred) {
    this.totalСoinsTransferred = totalСoinsTransferred;
  }

  public IOSummary totalFee(BigDecimal totalFee) {
    this.totalFee = totalFee;
    return this;
  }

   /**
   * Total fee
   * @return totalFee
  **/
  @Schema(example = "15.43", required = true, description = "Total fee")
  public BigDecimal getTotalFee() {
    return totalFee;
  }

  public void setTotalFee(BigDecimal totalFee) {
    this.totalFee = totalFee;
  }

  public IOSummary feePerByte(BigDecimal feePerByte) {
    this.feePerByte = feePerByte;
    return this;
  }

   /**
   * Fee per Byte
   * @return feePerByte
  **/
  @Schema(example = "4.21", required = true, description = "Fee per Byte")
  public BigDecimal getFeePerByte() {
    return feePerByte;
  }

  public void setFeePerByte(BigDecimal feePerByte) {
    this.feePerByte = feePerByte;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IOSummary ioSummary = (IOSummary) o;
    return Objects.equals(this.totalСoinsTransferred, ioSummary.totalСoinsTransferred) &&
        Objects.equals(this.totalFee, ioSummary.totalFee) &&
        Objects.equals(this.feePerByte, ioSummary.feePerByte);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalСoinsTransferred, totalFee, feePerByte);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IOSummary {\n");
    
    sb.append("    totalСoinsTransferred: ").append(toIndentedString(totalСoinsTransferred)).append("\n");
    sb.append("    totalFee: ").append(toIndentedString(totalFee)).append("\n");
    sb.append("    feePerByte: ").append(toIndentedString(feePerByte)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
