/*
 * Ergo blockchain explorer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * An object containing all components of pow solution
 */
@Schema(description = "An object containing all components of pow solution")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-09T08:14:50.203Z[GMT]")
public class PowSolutions {
  @SerializedName("pk")
  private String pk = null;

  @SerializedName("w")
  private String w = null;

  @SerializedName("n")
  private String n = null;

  @SerializedName("d")
  private Integer d = null;

  public PowSolutions pk(String pk) {
    this.pk = pk;
    return this;
  }

   /**
   * Base16-encoded public key
   * @return pk
  **/
  @Schema(example = "0350e25cee8562697d55275c96bb01b34228f9bd68fd9933f2a25ff195526864f5", required = true, description = "Base16-encoded public key")
  public String getPk() {
    return pk;
  }

  public void setPk(String pk) {
    this.pk = pk;
  }

  public PowSolutions w(String w) {
    this.w = w;
    return this;
  }

   /**
   * Get w
   * @return w
  **/
  @Schema(example = "0366ea253123dfdb8d6d9ca2cb9ea98629e8f34015b1e4ba942b1d88badfcc6a12", required = true, description = "")
  public String getW() {
    return w;
  }

  public void setW(String w) {
    this.w = w;
  }

  public PowSolutions n(String n) {
    this.n = n;
    return this;
  }

   /**
   * Get n
   * @return n
  **/
  @Schema(example = "0000000000000000", required = true, description = "")
  public String getN() {
    return n;
  }

  public void setN(String n) {
    this.n = n;
  }

  public PowSolutions d(Integer d) {
    this.d = d;
    return this;
  }

   /**
   * Get d
   * @return d
  **/
  @Schema(example = "987654321", required = true, description = "")
  public Integer getD() {
    return d;
  }

  public void setD(Integer d) {
    this.d = d;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PowSolutions powSolutions = (PowSolutions) o;
    return Objects.equals(this.pk, powSolutions.pk) &&
        Objects.equals(this.w, powSolutions.w) &&
        Objects.equals(this.n, powSolutions.n) &&
        Objects.equals(this.d, powSolutions.d);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pk, w, n, d);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PowSolutions {\n");
    
    sb.append("    pk: ").append(toIndentedString(pk)).append("\n");
    sb.append("    w: ").append(toIndentedString(w)).append("\n");
    sb.append("    n: ").append(toIndentedString(n)).append("\n");
    sb.append("    d: ").append(toIndentedString(d)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
