/*
 * Ergo blockchain explorer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Timespan for charts
 */
@JsonAdapter(Timespan.Adapter.class)
public enum Timespan {
  ALL("all"),
  _7DAYS("7days"),
  _30DAYS("30days"),
  _60DAYS("60days"),
  _180DAYS("180days"),
  _1YEAR("1year"),
  _2YEARS("2years");

  private String value;

  Timespan(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Timespan fromValue(String text) {
    for (Timespan b : Timespan.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Timespan> {
    @Override
    public void write(final JsonWriter jsonWriter, final Timespan enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Timespan read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Timespan.fromValue(String.valueOf(value));
    }
  }
}
