/*
 * Ergo blockchain explorer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.explorer.client.model.SpendingProof;
/**
 * UnconfirmedTransactionInput
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-09T08:14:50.203Z[GMT]")
public class UnconfirmedTransactionInput {
  @SerializedName("boxId")
  private String boxId = null;

  @SerializedName("spendingProof")
  private SpendingProof spendingProof = null;

  public UnconfirmedTransactionInput boxId(String boxId) {
    this.boxId = boxId;
    return this;
  }

   /**
   * Get boxId
   * @return boxId
  **/
  @Schema(required = true, description = "")
  public String getBoxId() {
    return boxId;
  }

  public void setBoxId(String boxId) {
    this.boxId = boxId;
  }

  public UnconfirmedTransactionInput spendingProof(SpendingProof spendingProof) {
    this.spendingProof = spendingProof;
    return this;
  }

   /**
   * Get spendingProof
   * @return spendingProof
  **/
  @Schema(required = true, description = "")
  public SpendingProof getSpendingProof() {
    return spendingProof;
  }

  public void setSpendingProof(SpendingProof spendingProof) {
    this.spendingProof = spendingProof;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnconfirmedTransactionInput unconfirmedTransactionInput = (UnconfirmedTransactionInput) o;
    return Objects.equals(this.boxId, unconfirmedTransactionInput.boxId) &&
        Objects.equals(this.spendingProof, unconfirmedTransactionInput.spendingProof);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boxId, spendingProof);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnconfirmedTransactionInput {\n");
    
    sb.append("    boxId: ").append(toIndentedString(boxId)).append("\n");
    sb.append("    spendingProof: ").append(toIndentedString(spendingProof)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
