-- UPDATE NAME_COVERT to MIXING_COVERT_REQUEST

-- !Ups
ALTER TABLE MIXING_COVERT_REQUEST ADD NAME_COVERT     VARCHAR(255) DEFAULT '';

-- !Downs
ALTER TABLE MIXING_COVERT_REQUEST DROP NAME_COVERT;


