 -- UPDATE IS_MANUAL_COVERT to MIXING_COVERT_REQUEST

-- !Ups
ALTER TABLE MIXING_COVERT_REQUEST ADD IS_MANUAL_COVERT BOOLEAN DEFAULT false;

-- !Downs
ALTER TABLE MIXING_COVERT_REQUEST DROP IS_MANUAL_COVERT;
