-- !Ups
CREATE TABLE HOP_MIX
(
    MIX_ID       VARCHAR(255) not null,
    ROUND        INT          not null,
    CREATED_TIME BIGINT,
    BOX_ID       VARCHAR(255),
    primary key (MIX_ID, ROUND),
    check (("ROUND" >= 0)),
    check (("CREATED_TIME" >= 0))
);

ALTER TABLE RESCAN ADD BOX_TYPE     VARCHAR(255);
UPDATE RESCAN SET BOX_TYPE = 'full' WHERE IS_HALF_MIX_TX = false;
UPDATE RESCAN SET BOX_TYPE = 'half' WHERE IS_HALF_MIX_TX = true;
ALTER TABLE RESCAN DROP IS_HALF_MIX_TX;
ALTER TABLE RESCAN_ARCHIVE ADD BOX_TYPE     VARCHAR(255);
UPDATE RESCAN_ARCHIVE SET BOX_TYPE = 'full' WHERE IS_HALF_MIX_TX = false;
UPDATE RESCAN_ARCHIVE SET BOX_TYPE = 'half' WHERE IS_HALF_MIX_TX = true;
ALTER TABLE RESCAN_ARCHIVE DROP IS_HALF_MIX_TX;


-- !Downs
DROP TABLE HOP_MIX

ALTER TABLE RESCAN DROP BOX_TYPE;
UPDATE RESCAN SET IS_HALF_MIX_TX = false WHERE BOX_TYPE = 'full';
UPDATE RESCAN SET IS_HALF_MIX_TX = true WHERE BOX_TYPE = 'half';
ALTER TABLE RESCAN ADD IS_HALF_MIX_TX     BOOLEAN;
ALTER TABLE RESCAN_ARCHIVE ADD IS_HALF_MIX_TX     VARCHAR(255);
UPDATE RESCAN_ARCHIVE SET IS_HALF_MIX_TX = false WHERE BOX_TYPE = 'full';
UPDATE RESCAN_ARCHIVE SET IS_HALF_MIX_TX = true WHERE BOX_TYPE = 'half';
ALTER TABLE RESCAN_ARCHIVE DROP BOX_TYPE;

