/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 0.1
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * BlockADProofs
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-10-19T14:53:04.559Z[GMT]")
public class BlockADProofs {
  @SerializedName("headerId")
  private String headerId = null;

  @SerializedName("proofBytes")
  private String proofBytes = null;

  @SerializedName("digest")
  private String digest = null;

  @SerializedName("size")
  private Integer size = null;

  public BlockADProofs headerId(String headerId) {
    this.headerId = headerId;
    return this;
  }

   /**
   * Get headerId
   * @return headerId
  **/
  @Schema(required = true, description = "")
  public String getHeaderId() {
    return headerId;
  }

  public void setHeaderId(String headerId) {
    this.headerId = headerId;
  }

  public BlockADProofs proofBytes(String proofBytes) {
    this.proofBytes = proofBytes;
    return this;
  }

   /**
   * Get proofBytes
   * @return proofBytes
  **/
  @Schema(required = true, description = "")
  public String getProofBytes() {
    return proofBytes;
  }

  public void setProofBytes(String proofBytes) {
    this.proofBytes = proofBytes;
  }

  public BlockADProofs digest(String digest) {
    this.digest = digest;
    return this;
  }

   /**
   * Get digest
   * @return digest
  **/
  @Schema(required = true, description = "")
  public String getDigest() {
    return digest;
  }

  public void setDigest(String digest) {
    this.digest = digest;
  }

  public BlockADProofs size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Size in bytes
   * @return size
  **/
  @Schema(required = true, description = "Size in bytes")
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockADProofs blockADProofs = (BlockADProofs) o;
    return Objects.equals(this.headerId, blockADProofs.headerId) &&
        Objects.equals(this.proofBytes, blockADProofs.proofBytes) &&
        Objects.equals(this.digest, blockADProofs.digest) &&
        Objects.equals(this.size, blockADProofs.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headerId, proofBytes, digest, size);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockADProofs {\n");
    
    sb.append("    headerId: ").append(toIndentedString(headerId)).append("\n");
    sb.append("    proofBytes: ").append(toIndentedString(proofBytes)).append("\n");
    sb.append("    digest: ").append(toIndentedString(digest)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
