/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 0.1
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Emssion info for height
 */
@Schema(description = "Emssion info for height")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-10-19T14:53:04.559Z[GMT]")
public class EmissionInfo {
  @SerializedName("minerReward")
  private Long minerReward = null;

  @SerializedName("totalCoinsIssued")
  private Long totalCoinsIssued = null;

  @SerializedName("totalRemainCoins")
  private Long totalRemainCoins = null;

  public EmissionInfo minerReward(Long minerReward) {
    this.minerReward = minerReward;
    return this;
  }

   /**
   * Get minerReward
   * @return minerReward
  **/
  @Schema(description = "")
  public Long getMinerReward() {
    return minerReward;
  }

  public void setMinerReward(Long minerReward) {
    this.minerReward = minerReward;
  }

  public EmissionInfo totalCoinsIssued(Long totalCoinsIssued) {
    this.totalCoinsIssued = totalCoinsIssued;
    return this;
  }

   /**
   * Get totalCoinsIssued
   * @return totalCoinsIssued
  **/
  @Schema(description = "")
  public Long getTotalCoinsIssued() {
    return totalCoinsIssued;
  }

  public void setTotalCoinsIssued(Long totalCoinsIssued) {
    this.totalCoinsIssued = totalCoinsIssued;
  }

  public EmissionInfo totalRemainCoins(Long totalRemainCoins) {
    this.totalRemainCoins = totalRemainCoins;
    return this;
  }

   /**
   * Get totalRemainCoins
   * @return totalRemainCoins
  **/
  @Schema(description = "")
  public Long getTotalRemainCoins() {
    return totalRemainCoins;
  }

  public void setTotalRemainCoins(Long totalRemainCoins) {
    this.totalRemainCoins = totalRemainCoins;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmissionInfo emissionInfo = (EmissionInfo) o;
    return Objects.equals(this.minerReward, emissionInfo.minerReward) &&
        Objects.equals(this.totalCoinsIssued, emissionInfo.totalCoinsIssued) &&
        Objects.equals(this.totalRemainCoins, emissionInfo.totalRemainCoins);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minerReward, totalCoinsIssued, totalRemainCoins);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmissionInfo {\n");
    
    sb.append("    minerReward: ").append(toIndentedString(minerReward)).append("\n");
    sb.append("    totalCoinsIssued: ").append(toIndentedString(totalCoinsIssued)).append("\n");
    sb.append("    totalRemainCoins: ").append(toIndentedString(totalRemainCoins)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
