/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 0.1
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ErgoTransactionInput
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-10-19T14:53:04.559Z[GMT]")
public class ErgoTransactionInput {
  @SerializedName("boxId")
  private String boxId = null;

  @SerializedName("spendingProof")
  private SpendingProof spendingProof = null;

  public ErgoTransactionInput boxId(String boxId) {
    this.boxId = boxId;
    return this;
  }

   /**
   * Get boxId
   * @return boxId
  **/
  @Schema(required = true, description = "")
  public String getBoxId() {
    return boxId;
  }

  public void setBoxId(String boxId) {
    this.boxId = boxId;
  }

  public ErgoTransactionInput spendingProof(SpendingProof spendingProof) {
    this.spendingProof = spendingProof;
    return this;
  }

   /**
   * Get spendingProof
   * @return spendingProof
  **/
  @Schema(required = true, description = "")
  public SpendingProof getSpendingProof() {
    return spendingProof;
  }

  public void setSpendingProof(SpendingProof spendingProof) {
    this.spendingProof = spendingProof;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErgoTransactionInput ergoTransactionInput = (ErgoTransactionInput) o;
    return Objects.equals(this.boxId, ergoTransactionInput.boxId) &&
        Objects.equals(this.spendingProof, ergoTransactionInput.spendingProof);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boxId, spendingProof);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErgoTransactionInput {\n");
    
    sb.append("    boxId: ").append(toIndentedString(boxId)).append("\n");
    sb.append("    spendingProof: ").append(toIndentedString(spendingProof)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
