/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 0.1
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse2001
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-10-19T14:53:04.559Z[GMT]")
public class InlineResponse2001 {
  @SerializedName("isInitialized")
  private Boolean isInitialized = null;

  @SerializedName("isUnlocked")
  private Boolean isUnlocked = null;

  public InlineResponse2001 isInitialized(Boolean isInitialized) {
    this.isInitialized = isInitialized;
    return this;
  }

   /**
   * true if wallet is initialized, false otherwise
   * @return isInitialized
  **/
  @Schema(required = true, description = "true if wallet is initialized, false otherwise")
  public Boolean isIsInitialized() {
    return isInitialized;
  }

  public void setIsInitialized(Boolean isInitialized) {
    this.isInitialized = isInitialized;
  }

  public InlineResponse2001 isUnlocked(Boolean isUnlocked) {
    this.isUnlocked = isUnlocked;
    return this;
  }

   /**
   * true if wallet is unlocked, false otherwise
   * @return isUnlocked
  **/
  @Schema(required = true, description = "true if wallet is unlocked, false otherwise")
  public Boolean isIsUnlocked() {
    return isUnlocked;
  }

  public void setIsUnlocked(Boolean isUnlocked) {
    this.isUnlocked = isUnlocked;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.isInitialized, inlineResponse2001.isInitialized) &&
        Objects.equals(this.isUnlocked, inlineResponse2001.isUnlocked);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isInitialized, isUnlocked);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    isInitialized: ").append(toIndentedString(isInitialized)).append("\n");
    sb.append("    isUnlocked: ").append(toIndentedString(isUnlocked)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
